doctrine:
    dbal:
        driver: 'pdo_pgsql'
        server_version: 14.1
        charset: utf8
        url: '%env(resolve:DATABASE_URL)%'
        types:
            bool[]: MartinGeorgiev\Doctrine\DBAL\Types\BooleanArray
            smallint[]: MartinGeorgiev\Doctrine\DBAL\Types\SmallIntArray
            integer[]: MartinGeorgiev\Doctrine\DBAL\Types\IntegerArray
            bigint[]: MartinGeorgiev\Doctrine\DBAL\Types\BigIntArray
            text[]: MartinGeorgiev\Doctrine\DBAL\Types\TextArray
            jsonb: MartinGeorgiev\Doctrine\DBAL\Types\Jsonb
            jsonb[]: MartinGeorgiev\Doctrine\DBAL\Types\JsonbArray
        mapping_types:
            bool[]: bool[]
            _bool: bool[]
            smallint[]: smallint[]
            _int2: smallint[]
            integer[]: integer[]
            _int4: integer[]
            bigint[]: bigint[]
            _int8: bigint[]
            text[]: text[]
            _text: text[]
            jsonb: jsonb
            jsonb[]: jsonb[]
            _jsonb: jsonb[]
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Esb:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Esb/In'
                prefix: 'App\Esb\In'
                alias: Esb
