symfony_health_check:
    health_checks:
        -   id: symfony_health_check.doctrine_check
        -   id: symfony_health_check.redis_check
    configs:
        -   env: redis=%env(REDIS_LOCK_HOST)%
